// Export and Share Service
// Handles exporting explanations, diagrams, and sharing functionality

export interface ExportOptions {
  format: "pdf" | "markdown" | "html" | "json";
  includeCode: boolean;
  includeExplanation: boolean;
  includeVisualization: boolean;
  includeComplexity: boolean;
}

export interface ShareLink {
  id: string;
  url: string;
  expiresAt?: Date;
  accessCount: number;
}

class ExportService {
  public exportToMarkdown(
    code: string,
    explanation: string,
    complexity: { time: string; space: string },
    options: Partial<ExportOptions> = {}
  ): string {
    const opts: ExportOptions = {
      format: "markdown",
      includeCode: true,
      includeExplanation: true,
      includeVisualization: false,
      includeComplexity: true,
      ...options,
    };

    let markdown = "# Code Analysis Report\n\n";

    if (opts.includeCode) {
      markdown += "## Code\n\n```\n";
      markdown += code;
      markdown += "\n```\n\n";
    }

    if (opts.includeExplanation) {
      markdown += "## Explanation\n\n";
      markdown += explanation;
      markdown += "\n\n";
    }

    if (opts.includeComplexity) {
      markdown += "## Complexity Analysis\n\n";
      markdown += `- **Time Complexity:** ${complexity.time}\n`;
      markdown += `- **Space Complexity:** ${complexity.space}\n\n`;
    }

    markdown += `\n---\n*Generated by CodeViz AI*\n`;

    return markdown;
  }

  public exportToHTML(
    code: string,
    explanation: string,
    complexity: { time: string; space: string },
    options: Partial<ExportOptions> = {}
  ): string {
    const opts: ExportOptions = {
      format: "html",
      includeCode: true,
      includeExplanation: true,
      includeVisualization: false,
      includeComplexity: true,
      ...options,
    };

    return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Code Analysis Report</title>
  <style>
    body { font-family: Arial, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; }
    pre { background: #f4f4f4; padding: 15px; border-radius: 5px; overflow-x: auto; }
    h1 { color: #333; }
    h2 { color: #666; margin-top: 30px; }
    .complexity { background: #e8f4f8; padding: 15px; border-radius: 5px; margin: 20px 0; }
  </style>
</head>
<body>
  <h1>Code Analysis Report</h1>
  
  ${opts.includeCode ? `
    <h2>Code</h2>
    <pre><code>${this.escapeHtml(code)}</code></pre>
  ` : ""}
  
  ${opts.includeExplanation ? `
    <h2>Explanation</h2>
    <p>${this.escapeHtml(explanation)}</p>
  ` : ""}
  
  ${opts.includeComplexity ? `
    <h2>Complexity Analysis</h2>
    <div class="complexity">
      <p><strong>Time Complexity:</strong> ${complexity.time}</p>
      <p><strong>Space Complexity:</strong> ${complexity.space}</p>
    </div>
  ` : ""}
  
  <hr>
  <p><em>Generated by CodeViz AI</em></p>
</body>
</html>
    `.trim();
  }

  public exportToJSON(
    code: string,
    explanation: string,
    complexity: { time: string; space: string },
    metadata: Record<string, any> = {}
  ): string {
    const data = {
      code,
      explanation,
      complexity,
      metadata: {
        ...metadata,
        exportedAt: new Date().toISOString(),
      },
    };

    return JSON.stringify(data, null, 2);
  }

  public downloadFile(content: string, filename: string, mimeType: string): void {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  public generateShareLink(
    code: string,
    explanation: string,
    expiresInDays: number = 30
  ): ShareLink {
    // In a real implementation, this would create a shareable link via backend
    // For now, we'll use a data URL approach (limited by browser URL length)
    const data = btoa(JSON.stringify({ code, explanation }));
    const id = `share-${Date.now()}`;
    const url = `${window.location.origin}/share/${id}`;

    const shareLink: ShareLink = {
      id,
      url,
      expiresAt: new Date(Date.now() + expiresInDays * 24 * 60 * 60 * 1000),
      accessCount: 0,
    };

    // Store in localStorage for demo purposes
    const shareLinks = JSON.parse(localStorage.getItem("shareLinks") || "[]");
    shareLinks.push(shareLink);
    localStorage.setItem("shareLinks", JSON.stringify(shareLinks));

    return shareLink;
  }

  public generateEmbedCode(shareId: string, width: number = 800, height: number = 600): string {
    return `<iframe src="${window.location.origin}/embed/${shareId}" width="${width}" height="${height}" frameborder="0"></iframe>`;
  }

  private escapeHtml(text: string): string {
    const div = document.createElement("div");
    div.textContent = text;
    return div.innerHTML;
  }
}

export const exportService = new ExportService();

